import jsPDF from 'jspdf';
import 'jspdf-autotable';

export const generateStudentReport = (studentData) => {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(18);
  doc.text('KENYA SCHOOL MANAGEMENT SYSTEM', 20, 20);
  doc.setFontSize(14);
  doc.text('KCSE-Style Academic Report', 20, 30);

  // Student Info
  doc.setFontSize(12);
  doc.text(`Name: ${studentData.name}`, 20, 50);
  doc.text(`Admission No: ${studentData.admissionNumber}`, 20, 60);
  doc.text(`Form: ${studentData.form} ${studentData.stream || ''}`, 20, 70);
  doc.text(`Exam Type: ${studentData.examType}, Year: ${studentData.year}`, 20, 80);

  // Table of Marks
  const tableColumn = ["Subject", "Marks"];
  const tableRows = Object.entries(studentData.marks).map(([subject, mark]) => [
    subject,
    mark
  ]);

  doc.autoTable({
    head: [tableColumn],
    body: tableRows,
    startY: 90
  });

  // Summary
  const finalY = doc.lastAutoTable.finalY + 10;
  doc.text(`Total Marks: ${studentData.totalMarks}`, 20, finalY);
  doc.text(`Average: ${studentData.average}%`, 20, finalY + 10);
  doc.text(`Grade: ${studentData.grade}`, 20, finalY + 20);

  // Footer
  doc.setFontSize(10);
  doc.text('Generated by Kenya School Management System', 20, doc.internal.pageSize.height - 20);

  // Save PDF
  doc.save(`Report_${studentData.name}.pdf`);
};